### ISSUE TITLE
Priorizar Tarea

### ISSUE THREAD

**Issue by jalfling** [kirevey/cc6401_placeholder#7]
Como usuario
Quiero ordenar una tarea
Para subirle o bajarle la prioridad

**Comment by Lapnis** [comment]
## Notas Trabajo 26/04

- Se agregan botones para subir y bajar las tareas en la lista.

- Se asume que desde el controlador se mandan las tareas ordenadas por prioridad. Además, se debe mandar (en caso de que existan 1 o más tareas), la prioridad de la tarea con mayor y con menor prioridad, para de esta manera, identificar en el html cuando no se muestran los botones up y down (momentaneamente para probar la funcionalidad, se uso la pk para estos datos).

- Queda pendiente los test.

**Comment by adderou** [comment]
# Notas Trabajo 27/04
- Se agrega en el modelo la propiedad "priority"
- Se realizan los tests para modelo
- Se crean los métodos `moveUp()` y `moveDown()`
